# Site settings
title: Everton Nikolas de Oliveira
email: nikolas.mandaji@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://enoliveira.github.io" # the base hostname & protocol for your site
github_username:  enikolas

# Build settings
markdown: kramdown
encoding: UTF-8
